core/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name='core'
urlpatterns = [
    path('druzyna/', views.druzyna, name='druzyna'),
    path('<int:pk>/panel_zawodnika', views.pan_zawodnika, name='pan_zawodnika'),
    path('panel_trenera/', views.pan_trenera, name='pan_trenera'),
    path('zaloguj/', views.our_log, name='our_log'),
    path('choose/', views.choose, name='choose'),
    path('', views.index, name='index'),
    path('thx/', views.thx, name= 'thank'),
    path('<int:user_id>/', views.user_page, name='user_page'),
    path('<int:user_player_id>/player_page', views.player_page, name='player_page'),
    path('<int:team_id>/team_page', views.team_page, name='team_page'),
    path(r'signup/', views.signup, name='signup'),
    path('admin/', admin.site.urls),
]

final_final/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('mecze/', include('polls.urls')),
    path(r'', include('core.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path

from . import views

app_name='polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name="name"),

    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),

    path('<int:question_id>/vote/', views.vote, name='vote'),
]

polls/models.py
from django.db import models

# Create your models here.
class Question(models.Model):

    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('data_wystawienia')
    data_wydarzenia = models.DateTimeField("Data meczu/treningu:")
    

    def __str__(self):
        return self.question_text

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect

from django.urls import reverse
from django.views import generic

from .models import Question, Choice
# Create your views here.

class IndexView(generic.ListView):

    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        return Question.objects.order_by('-pub_date')[:5]

    

class DetailView(generic.DetailView):

    model = Question
    template_name = 'polls/detail.html'

class ResultsView(generic.DetailView):

    model = Question
    template_name = 'polls/results.html'

def vote(request, question_id):

    question = get_object_or_404(Question, pk=question_id)

    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])

    except (KeyError, Choice.DoesNotExist):
        
        return render(request, 'polls/detail.html', {'question': question, 'error_message': "Nie wybrales!",})
    
    else:
        selected_choice.votes += 1
        selected_choice.save()

        return HttpResponseRedirect(reverse('polls:results', args=(question_id,)))


    return HttpResponse("Glosujesz w wydarzeniu numer %s." % question_id)

templates/polls/base.html
{% load static %}

<html lang="en">
<head>
    <title>TeamUp</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
</head>
<body>
    <h1 id="typography">Witaj</h1>

        {% block content %}
                
        {% endblock content %}
    
</body>
</html>

templates/polls/detail.html
{% extends 'polls/base.html' %}

{% block content %}
<h1 id="typography">{{ question.question_text }}- {{question.data_wydarzenia}}</h1>

{% if error_message %} <p><strong>{{error_message}} </strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name='choice' id='choice{{ forloop.counter }}' value="{{choice.id}}"/>
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
    {% endfor %}
    <input type="submit" value="Potwierdz"/>

</form>
                
{% endblock content %}

templates/polls/index.html
{% extends 'polls/base.html' %}

{% block content %}

<h1 id="typography">Nadchodzace mecze i treningi</h1>
{% if latest_question_list %}
    <!-- <ul> -->
        {% for question in latest_question_list %}

        <ul>
                <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }} - {{question.data_wydarzenia}} </a></li>
            {% for choice in question.choice_set.all %}
               
                <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize}}</li>
            {% endfor %}
        </ul>

            
        {% endfor %}
    <!-- </ul> -->
{% else %}
    <p>Wydarzenie nie jest dostpene</p>
{% endif %}

{% endblock content %}

templates/polls/results.html
{% extends 'polls/base.html' %}

{% block content %}

<h1 id="typography">{{ question.question_text }}</h1>

<ul>
    {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize}}</li>
    {% endfor %}
</ul>

<!-- <a href="{% url 'polls:detail' question.id %}">Zdecyduj jeszcze raz</a> | -->
 <a href="{% url 'polls:name' %}">Wroc do wydarzen</a>
                
{% endblock content %}