core/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name='core'
urlpatterns = [
    path('druzyna/', views.druzyna, name='druzyna'),
    path('<int:pk>/panel_zawodnika', views.pan_zawodnika, name='pan_zawodnika'),
    path('panel_trenera/', views.pan_trenera, name='pan_trenera'),
    path('zaloguj/', views.our_log, name='our_log'),
    path('choose/', views.choose, name='choose'),
    path('', views.index, name='index'),
    path('thx/', views.thx, name= 'thank'),
    path('<int:user_id>/', views.user_page, name='user_page'),
    path('<int:user_player_id>/player_page', views.player_page, name='player_page'),
    path('<int:team_id>/team_page', views.team_page, name='team_page'),
    path(r'signup/', views.signup, name='signup'),
    path('admin/', admin.site.urls),
]

final_final/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('mecze/', include('polls.urls')),
    path(r'', include('core.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path

from . import views

app_name='polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name="name"),

    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),

    path('<int:question_id>/vote/', views.vote, name='vote'),
]

core/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class Teams(models.Model):
    idteam = models.AutoField(db_column='idTeam', primary_key=True)  # Field name made lowercase.
    team_name = models.CharField(db_column='Team_name', max_length=45)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Teams'

    def __str__(self):
        return '%s' % (self.team_name)

class Users(models.Model):
    iduser = models.AutoField(db_column='idUser', primary_key=True)  # Field name made lowercase.
    user_mail = models.CharField(db_column='User_mail', max_length=320, blank=True, null=True)  # Field name made lowercase.
    password = models.CharField(db_column='Password', max_length=32, blank=True, null=True)  # Field name made lowercase.
    role = models.IntegerField(db_column='Role', blank=True, null=True)  # Field name made lowercase.
    user_name = models.CharField(db_column='User_name', max_length=45, blank=True, null=True)  # Field name made lowercase.
    user_surname = models.CharField(db_column='User_surname', max_length=45, blank=True, null=True)  # Field name made lowercase.
    idteam = models.ForeignKey(Teams, on_delete= models.CASCADE,db_column='idTeam')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Users'

    def __str__(self):
        return self.user_name +" "+self.user_surname

class AuthGroup(models.Model):
    name = models.CharField(unique=True, max_length=80)

    class Meta:
        managed = False
        db_table = 'auth_group'


class AuthGroupPermissions(models.Model):
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)
    permission = models.ForeignKey('AuthPermission', models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_group_permissions'
        unique_together = (('group', 'permission'),)


class AuthPermission(models.Model):
    name = models.CharField(max_length=255)
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING)
    codename = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'auth_permission'
        unique_together = (('content_type', 'codename'),)


class AuthUser(models.Model):
    password = models.CharField(max_length=128)
    last_login = models.DateTimeField(blank=True, null=True)
    is_superuser = models.IntegerField()
    username = models.CharField(unique=True, max_length=150)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=150)
    email = models.CharField(max_length=254)
    is_staff = models.IntegerField()
    is_active = models.IntegerField()
    date_joined = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'auth_user'


class AuthUserGroups(models.Model):
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_groups'
        unique_together = (('user', 'group'),)


class AuthUserUserPermissions(models.Model):
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    permission = models.ForeignKey(AuthPermission, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_user_permissions'
        unique_together = (('user', 'permission'),)


class DjangoAdminLog(models.Model):
    action_time = models.DateTimeField()
    object_id = models.TextField(blank=True, null=True)
    object_repr = models.CharField(max_length=200)
    action_flag = models.PositiveSmallIntegerField()
    change_message = models.TextField()
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING, blank=True, null=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'django_admin_log'


class DjangoContentType(models.Model):
    app_label = models.CharField(max_length=100)
    model = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'django_content_type'
        unique_together = (('app_label', 'model'),)


class DjangoMigrations(models.Model):
    app = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    applied = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_migrations'


class DjangoSession(models.Model):
    session_key = models.CharField(primary_key=True, max_length=40)
    session_data = models.TextField()
    expire_date = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_session'

polls/models.py
from django.db import models

# Create your models here.
class Question(models.Model):

    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('data_wystawienia')
    data_wydarzenia = models.DateTimeField("Data meczu/treningu:")
    

    def __str__(self):
        return self.question_text

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

core/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.http import HttpResponse
from django.shortcuts import get_object_or_404

from .models import Teams, Users

# Create your views here.
def signup(request):
    form = UserCreationForm(request.POST)
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('home')

        else:
            form = UserCreationForm()
    return render(request, 'core/signup.html', {'form': form})

def index(request):

    num_Teams = Teams.objects.all().count()
    num_Users = Users.objects.all().count()

    return render(request, 'core/home_page.html', context={'num_Teams': num_Teams, 'num_Users':num_Users})

def choose(request):
    return render(request, 'core/choose.html')

def thx(request):
    return render(request, 'core/thank4reg.html')

def our_log(request):
    return render(request, 'core/index.html')

def druzyna(request):
    return render(request, 'core/druzyna.html')

def pan_trenera(request):

    all_Teams = Teams.objects.all()

    return render(request, 'core/panel_trenera.html', context={'all_Teams': all_Teams})

def pan_zawodnika(request, id_team):
    team = get_object_or_404(Teams, pk=id_team)
    return render(request, 'core/strona_glowna.html', {'team':team})

def user_page(request, user_id):
    return HttpResponse("Strona usera o id %s." % user_id)

def player_page(request, user_player_id):
    return HttpResponse('Strona dla zawodnika o id %s.' % user_player_id)

def team_page(requset, team_id):
    return HttpResponse('Strona druzyny o id %s.' % team_id)

templates/core/choose.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Wybierz swoja role</title>
    <link rel="stylesheet" href="{% static 'core/css/styll.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">
  </head>
  <body background="{% static 'core/img/zdjecie_startowe.jpg' %}" alt="kosz" style="width: 100%;">

    
    <div class="alert alert-dismissible alert-primary">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <strong>ZAREJESTRUJ</strong>
    </div>


    <form class="reg" action={% url 'core:thank' %} method="post">
      {% csrf_token %}

      <div class="form-group">
        <label for="exampleInputEmail1">Email address</label>
        <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
      </div>

      <div class="form-group">
        <label for="exampleInputPassword1">Password</label>
        <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
      </div>

      <input class="btn btn-primary btn-lg" type="submit" name="" value="Zaloz konto">

    </form>

  </body>
</html>

templates/core/druzyna.html
{% load static %}
<!DOCTYPE html>
<html lang="pl">
	<head>
		<meta charset="UTF-8">
		<title>Strona Głowna</title>
		<script src ="{% static 'core/js/druzynaJS.js' %}"></script>
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">
		<link rel="stylesheet" type="text/css" href="{% static 'core/css/strona_glownaCSS1.css' %}">

	</head>
<body background="{% static '/core/img/zdjecie_startowe.jpg' %}">

		<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="true" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="#">Drużyna <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'polls:name' %}">Terminarz</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Trening</a>
      </li>
         <li class="nav-item">
        <a class="nav-link" href="https://wrobasket.com/">Liga</a>
      </li>
       <li class="nav-item">
        <a class="nav-link" href="http://www.nba.com">Co nowego w NBA</a>
      </li>
    </ul>
  </div>
</nav>
  <ul style="color: aqua">
    <li>5 - Konrad</li>
    <li>4 - Krzysztof</li>
    <li>9 - Rycerz</li>
    <li>8 - Łatek</li>
    <li>6 - Hrycu</li>
    <li>13 - Dudi</li>
    <li>14 - Łuki</li>
  </ul>
</body>
</html>

templates/core/home_page.html
{% load static%}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Home Page</title>
    <link rel="stylesheet" href="{% static 'core/css/styll.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">
  </head>
  <body background="{% static 'core/img/zdjecie_startowe.jpg' %}" alt="kosz" style="width: 100%;">
{% block content %}

    <h1>Welcome to our Application</h1>
    <ul>
      <li><strong>Druzyny:</strong> {{ num_Teams }}</li>
      <li><strong>Uzytkownicy:</strong> {{ num_Users }}</li>
    </ul>
{% endblock %}
<form class="dwa_el" method="post">
  {% csrf_token %}
    <label for="el_2"></label>

  <a type="submit" class="btn btn-primary btn-lg" id="el_2" href="{% url 'core:choose' %}">Rejestracja </a>
   <a type="button" class="btn btn-primary btn-lg" href={% url 'core:our_log' %}> Zaloguj</a>

</form>



  </body>
</html>

templates/core/index.html
{% load static %}
<!DOCTYPE html>
<html lang="pl">
	<head>
		<meta charset="UTF-8">
		<title>Strona Głowna</title>
		<link rel="stylesheet" type="text/css" href="{% static 'core/css/mystyle.css' %}">
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">
		<link rel="stylesheet" type="text/css" href="{% static 'core/css/mystyleTEST.css' %}">
		<script type="myJavaScriptTEST.js"></script>
	</head>
	<body>
		<div class="container">
			<img src="{% static 'core/img/zdjecie_startowe.jpg' %}" alt="kosz" style="width: 100%;">
			<div class="centered">
				<button class="btnSTART" onclick="document.getElementById('id01').style.display='block'" >Zaloguj się</button>
			</div>

			<div id='id01' class="modal">

			<form class="modal-content animate" action={% url 'core:druzyna' %}>
				<div class="imgcontainer">
					<span onclick="document.getElementById('id01').style.display='none'" class="close" title="Zamknij">&times;</span>
					<img src="{% static 'core/img/bit_logowanie.jpg' %}" alt="Logowanie" class="avatar">
				</div>
				<div class="imgcontainer" style="text-align: left;">
					<label for="UserName"><b>Username</b></label>
					<input type="text" placeholder="Enter Username" name="UserName" required>

					<label for = "passW"><b>Password</b></label>
					<input type="password" placeholder="Enter Password" name="passW" required>


					<button type="submit" class="btn">Login</button>
				</div>
			</form>

			</div>
		</div>
	</body>
</html>

templates/core/panel_trenera.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Witaj zawodniku</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'core/css/styll.css' %}">
  </head>
  <body background="{% static 'core/img/zdjecie_startowe.jpg' %}" alt="kosz" style="width: 100%;">
    <h1>Trener</h1>




        <h4>Choose Ur Team:</h4>
          {% block content %}
          <!-- {% if all_Teams %} -->
            <ul>
              {% for t in team.choice_set.all %}

              <li> <a href={% url 'pan_zawodnika' t.idteam %}>{{ t.team_name }}</a> </li>
              {% endfor %}
            </ul>
          {% else %}
            <p>Nie ma dostepnych druzyn.</p>
          {% endif %}

          {% endblock %}



  </body>
</html>

templates/core/signup.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">
  </head>
  <body>

    {% block content %}
      <h2>Sign up</h2>
      <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Sign up</button>
      </form>
    {% endblock %}

  </body>
</html>

templates/core/strona_glowna.html
{% load static %}
<!DOCTYPE html>
<html lang="pl">
	<head>
		<meta charset="UTF-8">
		<title>Strona Głowna</title>
		<script type="myJavaScript.js"></script>
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">
		<link rel="stylesheet" type="text/css" href="{% static 'core/css/strona_glownaCSS.css' %}">

	</head>
	<body>
		<div class="container">
			<img src="zdjecie_startowe.jpg" alt="kosz" style="width: 100%">
				<button type="button" class="btn btn-primary btn-lg">DRUŻYNA</button>
				<button type="button" class="btn btn-primary btn-lg" style="top: 30%">TERMINARZ</button>
				<button type="button" class="btn btn-primary btn-lg" style="top: 40%">LIGA</button>
				<button type="button" class="btn btn-primary btn-lg" style="top: 50%">TRENINGI</button>
		</div>
	</body>
</html>

templates/core/thank4reg.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Ending Registration</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'core/css/styll.css' %}">
  </head>
  <body background="{% static 'core/img/zdjecie_startowe.jpg' %}" alt="kosz" style="width: 100%;">
    <div class="alert alert-dismissible alert-primary">
      <h1><strong>Dziękujemy za rejestracje</strong></h1>
    </div>



    <form class="przedjdz_d" action={% url 'core:druzyna' %} method="post">
        {% csrf_token %}
      <input class="btn btn-primary btn-lg" type="submit" name="" value="Przejdz dalej">
    </form>

  </body>
</html>